services:
  pg:
    image: postgres:17-alpine
    restart: unless-stopped
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${PG_NAME}
      POSTGRES_USER: ${PG_USER}
      POSTGRES_PASSWORD: ${PG_PASS}
    volumes:
      - pg-data:/var/lib/postgresql/data
    ports:
      - ${PG_PORT}:5432

  # app:
  #   container_name: app
  #   build:
  #     context: .
  #     dockerfile: ./Dockerfile
  #     args:
  #       - APP_PORT=${APP_PORT}
  #   ports:
  #     - ${APP_PORT}:${APP_PORT}
  #   env_file:
  #     - .env
  #   environment:
  #     PG_USER: ${PG_USER}
  #     PG_PASS: ${PG_PASS}
  #     PG_NAME: ${PG_NAME}
  #     PG_HOST: pg
  #     PG_PORT: 5432
  #   depends_on:
  #     - pg

volumes:
  pg-data:
